# Generated by Django 4.2 on 2025-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
